--liquibase formatted sql
--changeset antoxakon:2  -- Формат: author:id
--comment: create table employes

create table if not exists employes
(
  id bigint generated by default as identity primary key,
  employee_id uuid   not null unique,
  last_name   varchar(255) not null unique,
  first_name  varchar(255),
  role        varchar(255) not null
);